---

  - debug:
      msg: " Copying Files for c3850 ..."

  - name: Abort task if there is not enough space
    fail: msg="There is not enough space for new image..."
    when:  space_fact|int < 0

  - name: Run show version command to capture flash output
    ios_command:
      commands: "show flash:"
    register: show_flash_platform

  - name: Set Go Signal for File prompts
    set_fact:
      prompt_go: "Go!"
    when: plat_c3850.image not in show_flash_platform.stdout[0]

  - debug:
      msg: "The image already exists in flash..."
    when: prompt_go is not defined

  - name: Disable prompts
    ios_config:
      lines: "file prompt quiet"
    when: prompt_go is defined

  - name: Copy image to flash
    ios_command:
      commands: "copy http://{{ transfer_server }}/{{ plat_c3850.image }} flash:{{ plat_c3850.image }}"
    vars:
      ansible_command_timeout: 3600
    when: prompt_go is defined

  - name: Re-enable able prompts
    ios_config:
      lines: "no file prompt quiet"
    when: prompt_go is defined
