---

 - name: Parse show version
   cli:
     command: show version
     #parser: "/etc/ansible/ios_upgrade/parsers/c3850/show_version.yml"
     parser: "/mnt/c/Users/ernher/Documents/Scripts/Ansible/ios_upgrade/parsers/c3850/show_version.yml"

 - name: Parse show flash
   cli:
     command: "show flash:"
     #parser: "/etc/ansible/ios_upgrade/parsers/c3850/show_flash.yml"
     parser: "/mnt/c/Users/ernher/Documents/Scripts/Ansible/ios_upgrade/parsers/c3850/show_flash.yml"


 - name: Set Version Fact
   set_fact:
      version_fact: "{{ version.matches[0] }}"
      confreg_fact: "{{ confreg.matches[0] }}"
      free_space_fact: "{{ free_space.matches[0] }}"
      used_space_fact: "{{ used_space.matches[0] }}"
      sw_check_fact: "16."

 - name: Set Space Variable
   set_fact:
      space_fact: "{{ free_space_fact|int - plat_c3850.size|int }}"

 - name: Set Green Light to begin copy file role
   set_fact:
      go_signal: "Go!"
   when: version_fact != plat_c3850.sw_check
