---

  - debug:
      msg: " Copying Files for c4500 ..."

  - name: Abort task if there is not enough space
    fail: msg="There is not enough space for new image..."
    when:  space_fact|int < 0

  - name: Run show bootflash command to capture bootflash output
    ios_command:
      commands: show bootflash
    register: show_bootflash_platform

  - name: Run show slavebootflash command to capture slavebootflash output
    ios_command:
      commands: show slavebootflash
    register: show_slavebootflash_platform

#  - debug:
#      var: show_bootflash_platform.stdout[0]

  - name: Set Go Singnal for File prompts
    set_fact:
      prompt_go: "Go!"
    when: plat_c4500.image not in show_bootflash_platform.stdout[0] and plat_c4500.image not in show_slavebootflash_platform.stdout[0]

  - debug:
      msg: "The image already exists in bootflash..."
    when: plat_c4500.image in show_bootflash_platform.stdout[0]

  - debug:
     msg: "The image already exists in bootflash..."
    when: plat_c4500.image in show_slavebootflash_platform.stdout[0]

  - name: Disable prompts
    ios_config:
      lines: "file prompt quiet"
    when: prompt_go is defined

  - name: Copy image to bootflash
    ios_command:
      commands: "copy http://{{ transfer_server }}/{{ plat_c4500.image }} bootflash:{{ plat_c4500.image }}"
    vars:
      ansible_command_timeout: 3600
    when: plat_c4500.image not in show_bootflash_platform.stdout[0]

  - name: Copy image to slavebootflash
    ios_command:
      commands: "copy http://{{ transfer_server }}/{{ plat_c4500.image }} slavebootflash:{{ plat_c4500.image }}"
    vars:
      ansible_command_timeout: 3600
    when: plat_c4500.image not in show_slavebootflash_platform.stdout[0]

  - name: Re-enable able prompts
    ios_config:
      lines: "no file prompt quiet"
    when: prompt_go is defined
