---

 - name: Parse show version
   cli:
     command: show version
     #parser: "/etc/ansible/ios_upgrade/parsers/c3850/show_version.yml"
     parser: "/mnt/c/Users/ernher/Documents/Scripts/Ansible/ios_upgrade/parsers/c9000/show_version.yml"

 - name: Parse show flash
   cli:
     command: "dir flash:"
     #parser: "/etc/ansible/ios_upgrade/parsers/c3850/show_flash.yml"
     parser: "/mnt/c/Users/ernher/Documents/Scripts/Ansible/ios_upgrade/parsers/c9000/show_flash.yml"

 - name: Set Version Fact
   set_fact:
      version_fact: "{{ version.matches[0] }}"
      confreg_fact: "{{ confreg.matches[0] }}"
      total_space_fact: "{{ total_space.matches[0] }}"
      used_space_fact: "{{ used_space.matches[0] }}"
      main_ver_train: "{{  main_ver_train.matches[0] }}"
      sec_ver_train: "{{  sec_ver_train.matches[0] }}"

 - name: Set Space Variable
   set_fact:
      space_fact: "{{ total_space_fact|int - plat_c9000.size|int }}"

 - name: Set Green Light to begin copy file role
   set_fact:
      go_signal: "Go!"
   when: version_fact != plat_c9000.sw_check

